import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from "@/components/header";
import Footer from '@/components/footer'
import FooterCopyright from '@/components/footer-copyright'
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        <FooterCopyright></FooterCopyright>
      </body>
    </html>
  )
}
